### ISSUE TITLE
Duplicate categories

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo-migrator-wordpress#10]
_From @perry-mitchell on October 11, 2015 8:56_

I transferred my site from wordpress to hexo, and I'm getting duplicate categories:
<img width="761" alt="screen shot 2015-10-11 at 11 54 10 am" src="https://cloud.githubusercontent.com/assets/3869469/10416088/d16c1240-700e-11e5-8b8b-eeead9d0e011.png">

These categories are present in db.json, and can be seen with `parent` fields - This is, I'm guessing, why there are duplicates being presented. I've checked over my posts and there doesn't seem to be any parent specification, eg:
```
title: 'A load balanced website using PHP FPM, Nginx, MySQL and Varnish (Part 1)'
tags:
  - nginx
  - varnish
  - wordpress
id: 79
categories:
  - MySQL
  - PHP
  - Programming
  - Software
date: 2013-07-01 08:23:21
---
```

I also don't have any categories directory or category map, so I don't know how Hexo is generating this list.

Hexo info:
```
hexo: 3.1.1
os: Darwin 15.0.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

_Copied from original issue: hexojs/hexo#1542_

**Comment by perry-mitchell** [comment]
How are the categories in the db.json file generated? All of the migrated files from wordpress contain _simple_ categories in a list, with no indication of parents. I can understand the migration being an issue, due to wordpress being tiered, but perhaps the cleanup would be easy if I knew were the categories were sourced from.

**Comment by leesei** [comment]
Can you try
```sh
hexo clean; rm db.json
hexo generate
```
and check `public/` again?

**Comment by perry-mitchell** [comment]
Cleaned as you suggested, but I still get the duplicates.

I have some posts like:
```
categories:
  - iOS
  - Software
```
and
```
categories:
  - General
  - iOS
  - Software
```

Would these cause problems? Wordpress had them nested, and I've used many for some posts.

In your example, why would 'b' be a child of anything? Wouldn't that be multiple categories?

**Comment by leesei** [comment]
Please accept the fact that *"Hexo does not support multiple categories"*.
With that in mind, you are on the edge case when migrating a WordPress site with multiple categories to Hexo.

To my understanding, each categories are represented with a unique id.
I guess the ids created in your post will be like (the numbers are arbitrary, just to illustrate the relationships):

```
categories:
  - iOS (id=1, parent=null)
  - Software (id=11, parent=1)
```
and
```
categories:
  - General (id=2, parent=null)
  - iOS (id=21, parent=2)
  - Software (id=211, parent=21)
```

So the "Software" with id 11 is different from "Software" of id 211, that explains the duplicate of "Software" category.

**Comment by perry-mitchell** [comment]
Well then why does the categories section of the post headers use an array? And why do most themes comma-separate categories?

I think I understand though, now. I'll have to go over all my posts to sanitise them. This process should be updated, because users in Wordpress may have multiple categories that are not ancestors.

**Comment by leesei** [comment]
Refer to issues on hexojs/hexo to discuss the rationale to (or not to) support multiple categories.
https://github.com/hexojs/hexo/issues/609
https://github.com/hexojs/hexo/issues/848

Closing this issue now.
