### ISSUE TITLE
Migrated images have broken path in img "src"

### ISSUE THREAD

**Issue by jashsayani** [hexojs/hexo-migrator-wordpress#101]
Migrator runs successfully with `import-image` flag:

![Screen Shot 2020-08-28 at 9 10 37 PM](https://user-images.githubusercontent.com/18684/91629000-e7f30700-e979-11ea-8303-5a4f3c9aa5ef.png)

Posts don't have images:

![Screen Shot 2020-08-28 at 9 55 49 PM](https://user-images.githubusercontent.com/18684/91629024-01944e80-e97a-11ea-8184-fb627b561fc4.png)

Using browser Dev Tools to inspect element, it shows a broken "src":

![Screen Shot 2020-08-28 at 9 56 43 PM](https://user-images.githubusercontent.com/18684/91629033-196bd280-e97a-11ea-8ac5-bc0e56f485ff.png)

**Comment by curbengh** [comment]
Can you attach the xml for "Automation and growing population" post? I'll test it out.

**Comment by jashsayani** [comment]
> Can you attach the xml for "Automation and growing population" post? I'll test it out.

Its part of: https://github.com/hexojs/hexo-migrator-wordpress/issues/35#issuecomment-663810839

> Did you enable post_asset_folder in _config.yml?

Yes. Still the same issue.

> Did you use --import_image or --import_image original?

I used `--import_image`

**Comment by curbengh** [comment]
> Its part of: https://github.com/hexojs/hexo-migrator-wordpress/issues/35#issuecomment-663810839

I only tested with [xml](https://gist.github.com/adnan360/0b385ba56fbbbb8cfe6148e05150efaa) provided by @adnan360. In that xml, a post is located at `http://localhost/wp-hexotest/2020/07/04/post-with-image-classic-editor/`, so there is a date in the link, whereas yours is `http://www.jashsayani.com/airset-takes-your-desktop-to-the-cloud/`.

As for image metadata, @adnan360 version has `2020/07/greens-4926370_640.jpg` which correlates to its permalink `http://localhost/wp-hexotest/wp-content/uploads/2020/07/greens-4926370_640.jpg`, whereas yours is  `/home/www/jashsayani.com/wp-content/uploads/airset-contacts.png` with permalink `http://www.jashsayani.com/wp-content/uploads/airset-contacts.png`.

If `post_asset_folder` is enabled, it shouldn't make any difference. I'll investigate further.

**Comment by curbengh** [comment]
To be fixed in #103 

---

> ![](https://user-images.githubusercontent.com/18684/91629024-01944e80-e97a-11ea-8184-fb627b561fc4.png)

@jashsayani 

Once this issue is fixed, you shall see `<img src="huawei-bcom-qcom.jpg">`. This image is only valid in individual post and not in index page. See https://github.com/hexojs/hexo/issues/4454.

If you want those images to show up on index page as well, add the following config after you migrate the posts:

``` yml
#_config.yml
marked:
  prependRoot: true
  postAsset: true
```

This feature is available in hexo-renderer-marked 3.1.0+

**Comment by jashsayani** [comment]
> is enabled beforehand

you mean before the migrator is run? This should be added to `README` in that case.
