### ISSUE TITLE
Migrated images pointing on wp-content on Wordpress blog

### ISSUE THREAD

**Issue by jashsayani** [hexojs/hexo-migrator-wordpress#102]
Some posts using the URL from `wp-content` and pointing to hosted Wordpress blog

![Screen Shot 2020-08-29 at 9 03 18 PM](https://user-images.githubusercontent.com/18684/91650944-171d7d00-ea3b-11ea-9814-b74aa8f2d6ba.png)

**Comment by curbengh** [comment]
Merged with https://github.com/hexojs/hexo-migrator-wordpress/issues/101
