### ISSUE TITLE
invalid error

### ISSUE THREAD

**Issue by jinzizhe** [hexojs/hexo-migrator-wordpress#105]
[root@web blog.jinzz.cc]# hexo migrate wordpress /root/WordPress.xml 
INFO  Validating config
INFO  Analyzing /root/WordPress.xml...
FATAL {
  err: Error: Error: invalid format
      at Hexo.module.exports (/home/wwwroot/xxxx/node_modules/hexo-migrator-wordpress/lib/migrator.js:77:11)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

Not sure what went wrong, the WordPress.xml file was exported by my Wordpress site and i believe there is noting wrong with the xml file.
Any help would be apearciate.

**Comment by curbengh** [comment]
Can I have a look at the xml?

**Comment by jinzizhe** [comment]
I have remove all the Chinese character in the xml file, hope that did not interfere your judgment

**Comment by jinzizhe** [comment]
[WordPress.2020-08-30.zip](https://github.com/hexojs/hexo-migrator-wordpress/files/5146772/WordPress.2020-08-30.zip)

**Comment by curbengh** [comment]
Somehow the xml parser ([camaro](https://github.com/tuananh/camaro)) couldn't read your xml. I glanced through the file and the syntax looked fine. Can I use your xml to submit bug report to the camaro?

**Comment by jinzizhe** [comment]
Thank you so much for your reply and I have found the problem.
In line 20136 there is a ^Q and in line 25599 there is a ^@. After I delete this 2 character, it migrate successfully.

**Comment by curbengh** [comment]
I see, they seem to be unprintable characters? Anyhow, I will submit a bug report to camaro, those characters should be ignored.
