### ISSUE TITLE
Quotes in Title Failure

### ISSUE THREAD

**Issue by mlafleur** [hexojs/hexo-migrator-wordpress#17]
When processing my Wordpress site, I had 3 entries with quotes (&#034;) in the Title. These entries generate the following error during migration: 

> YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
>     date: 2003-08-08 18:17:00

**Comment by dengshilong** [comment]
In my [repository](https://github.com/dengshilong/hexo-migrator-wordpress.git), it doesn't this problem .  You can run `npm install https://github.com/dengshilong/hexo-migrator-wordpress.git --save`, then process Wordpress migrate.

**Comment by dengshilong** [comment]
I find this problem have solved in [hexo-migrator-wordpress](https://github.com/hexojs/hexo-migrator-wordpress.git), so just run `npm install https://github.com/hexojs/hexo-migrator-wordpress.git --save`, then process Wordpress,

**Comment by ottobonn** [comment]
@dengshilong's modifications fixed this crash for me. Thanks! Have you submitted a PR?

**Comment by dengshilong** [comment]
@ottobonn This problem have solved in master, but the hexo-migrator-wordpress plugin in NPM is out of date.
