### ISSUE TITLE
Problem importing posts with long titles 

### ISSUE THREAD

**Issue by albacoretuna** [hexojs/hexo-migrator-wordpress#19]
Thanks for the nice plugin. 

I'm trying to import my around 70 wordpress posts into hexo. Titles are in arabic alphabet and the unicode alphabets become like this: 
/source/_posts/d9-81-d9-86-d9-84-d8-a7-d9-86-d8-af-d9-85-d9-87-d9-85-d8-a7-d9-86-d8-a7-d9-81-d8-aa-d8-ae-d8-a7-d8-b1-db-8c-d9-86-d9-85-d8-a7-db-8c-d8-b4-da-af-d8-a7-d9-87-da-a9-d8-aa-d8-a7-d8-a8-d9-81-d8-b1.md

and I get errors like this on my ubuntu:

FATAL ENAMETOOLONG: name too long, open '/home/user/onfinland/source/_posts/d9-81-d9-86-d9-84-d8-a7-d9-86-d8-af-d9-85-d9-87-d9-85-d8-a7-d9-86-d8-a7-d9-81-d8-aa-d8-ae-d8-a7-d8-b1-db-8c-d9-86-d9-85-d8-a7-db-8c-d8-b4-da-af-d8-a7-d9-87-da-a9-d8-aa-d8-a7-d8-a8-d9-81-d8-b1.md'

**Comment by dengshilong** [comment]
You can run `npm install https://github.com/dengshilong/hexo-migrator-wordpress.git --save` , then process Wordpress migrate.

**Comment by curbengh** [comment]
2.0.0 supports unicode as filename. In this case, the imported post will be named: 'فنلاندمهمانافتخارینمایشگاهکتابفر.md'
