### ISSUE TITLE
Some problem when the post has <code> tag

### ISSUE THREAD

**Issue by YangXuran** [hexojs/hexo-migrator-wordpress#22]
When the post has two or more `<pre><code> </code></pre>` tags , the migrator will merge all the `<code> </code>` paragraphs.

Like this:
    `<pre><code>grub2-set-default 0</code></pre>`
then reboot
    `<pre><code>reboot</code></pre>`

After use migrator:
　　`<pre>grub2-set-default 0</pre>`
　　`reboot`
　　`<pre>reboot</pre>`

**Comment by curbengh** [comment]
After #65,

```
<pre><code>grub2-set-default 0</code></pre>
then reboot
<pre><code>reboot</code></pre>
```

is converted to:

<pre><code>```
grub2-set-default 0
```

then reboot

```
reboot
```</code></pre>
