### ISSUE TITLE
Migration doesn't work on Ubuntu 16.04

### ISSUE THREAD

**Issue by pwittchen** [hexojs/hexo-migrator-wordpress#25]
I typed:

```
npm install hexo-migrator-wordpress --save
```

then I got:

```
npm WARN saveError ENOENT: no such file or directory, open '/home/piotr/package.json'
/home/piotr
└── hexo-migrator-wordpress@0.1.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/home/piotr/package.json'
npm WARN piotr No description
npm WARN piotr No repository field.
npm WARN piotr No README data
npm WARN piotr No license field.
```

Next, when I typed:

```
hexo migrate wordpress myfile.xml
```

I got only help info:

```
Usage: hexo <command>

Commands:
  help     Get help on a command.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
```

and nothing was migrated.

I also tried:

```
npm install hexo-migrator-wordpress -g
```

with no luck.

My environment:

```
hexo version
```

```
hexo-cli: 1.0.4
os: Linux 4.4.0-112-generic linux x64
http_parser: 2.7.0
node: 7.10.1
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
```

System info:

```
OS: Ubuntu 16.04 xenial
Kernel: x86_64 Linux 4.4.0-112-generic
Shell: zsh 5.1.1
DE: Gnome
WM: GNOME Shell
```

I'll try this later on Mac, but I'd like to have it working on Ubuntu Linux as well.

**Comment by pwittchen** [comment]
I checked it on macOS and it doesn't work on that OS either. I reported it in #26.
Can you take a look at these issues?

**Comment by pwittchen** [comment]
I didn't use this migrator and ended up with some custom bash scripting, playing with vim and manual work. Nevertheless, I did it once, not planning to do it again and unfortunately don't have any production-ready generic solution to share.

**Comment by RichardJECooke** [comment]
Oh, here's the answer: https://www.arronwoods.com/blog/2017/03/hexo-missing-the-generate-and-server-commands/

Now it runs. Yay. But it just makes Markdown files, no photos/music are pulled from my site :(

**Comment by curbengh** [comment]
Works fine in Ubuntu Mate 16.04.6 + Nodejs 12.18.3

> no photos/music are pulled from my site

2.1.0+ supports importing photos when `--import-image` option is specified.


- Import original-sized and resized image attachments.
  * Usage: `$ hexo migrate wordpress /path/export.xml --import-image`
- There is an option to import original-size images only.
  * Usage: `$ hexo migrate wordpress /path/export.xml --import-image original`
