### ISSUE TITLE
exporting images?

### ISSUE THREAD

**Issue by jashsayani** [hexojs/hexo-migrator-wordpress#34]
My wordpress blog has a lot of images and the exported extended rss file only has the links to existing images hosted on my wordpress blog. I would expect the tools to `curl` the images and download them, and update the links in the post to the relative image paths to downloaded images.

**Comment by jashsayani** [comment]
I guess this is similar to #30

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-migrator-wordpress/issues/54

**Comment by curbengh** [comment]
Duplicate of #21
