### ISSUE TITLE
multiple categories exported as nested categories

### ISSUE THREAD

**Issue by jashsayani** [hexojs/hexo-migrator-wordpress#36]
I sometimes use multiple categories for a post. The hexo migrator has made them nested.

Exported with migrate:
```
categories:
  - Featured
  - Tutorial
```

Expected:
```
categories:
  - [Featured]
  - [Tutorial]
```

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-migrator-wordpress/issues/54

**Comment by curbengh** [comment]
Defaults to tags (not nested) since v2 https://github.com/hexojs/hexo-migrator-wordpress/pull/57

```
tags:
  - foo
  - bar
```

**Comment by curbengh** [comment]
Defaults to tags (not nested) since v2 https://github.com/hexojs/hexo-migrator-wordpress/pull/57

```
tags:
  - foo
  - bar
```

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-migrator-wordpress/pull/81

**Comment by curbengh** [comment]
From the [sample](https://github.com/hexojs/hexo-migrator-wordpress/issues/35#issuecomment-663810839), do you have any nested category?

**Comment by jashsayani** [comment]
many posts have 2 categories. they are migrated as nested instead of being 2 categories.

**Comment by curbengh** [comment]
I mean your original WP, I can't find any indication of nested category from the sample. I wonder what it looks like. @jehy @adnan360

**Comment by adnan360** [comment]
[Here](https://gist.github.com/adnan360/0b385ba56fbbbb8cfe6148e05150efaa) is an export with categories, sub categories and tags added to "Post with Image". Here's how it looks like on editor for reference:

![wp-multi-category-01](https://user-images.githubusercontent.com/7857310/88483184-06836e00-cf88-11ea-8b4a-7afbb6bdb71b.png)

**Comment by curbengh** [comment]
---

> I guess Hexo doesn't have non-hierarchical / non-nesting categories as discussed

``` yml
categories:
  - [Featured]
  - [Tutorial]
```

works for me. a theme might displays it as `Featured/Tutorial`, but when I check the link, it's not nested.

**Comment by adnan360** [comment]
> ...but when I check the link, it's not nested.
Oh, that's true! It works! The arrow in the default theme is confusing (at least for WP users like me). I guess I can just modify the theme to show it differently.

**Comment by curbengh** [comment]
> I guess I can just modify the theme to show it differently.

I haven't quite figure it out, feel free to upstream the fix to [hexo-theme-landscape](https://github.com/hexojs/hexo-theme-landscape).

``` yml
categories:
  - [Lorem, Ipsum, Dolor]
  - [Foo, Bar]
  - [Baz]
```

Perhaps display them as `Categories: Lorem => Ipsum => Dolor | Foo => Bar | Baz`.

**Comment by adnan360** [comment]
Well, I am used to WP side of things, not so much for Hexo, so not sure how to make edits for it (didn't have time to look into it yet). Created an [issue](https://github.com/hexojs/hexo-theme-landscape/issues/169) for this though.
