### ISSUE TITLE
invalid character entity

### ISSUE THREAD

**Issue by GerhardMes** [hexojs/hexo-migrator-wordpress#43]
I am using "&" entities in my blog. An got the error when migrating.

I only had to change the "&" to "and" - and everthing went smooth.
Thanks

**Comment by YoshinoriN** [comment]
@GerhardMes 
Thank you for your report.
We will try to investigate it.

**Comment by jehy** [comment]
Same here.
My post title XML was `<title><![CDATA[Some&quot;Title&quot;]]></title>` - and after import quotes were not rendered like it was in wordpress.

**Comment by curbengh** [comment]
`<p>a&bc&gt;</p>` content outputs `a&bc>&def`.
