### ISSUE TITLE
汉字乱码问题

### ISSUE THREAD

**Issue by liyaodong** [hexojs/hexo-migrator-wordpress#8]
当标题名为乱码时，写入本地的`md`文件是乱码

**Comment by Xuanwo** [comment]
那就不要让标题名乱码啊- -

统一使用UTF-8

**Comment by liyaodong** [comment]
- -
我导出的 `wordpress` `xml` 是好的，没有任何乱码
然后 `hexo migrate`之后 `/source/_post` 下的文件名都是乱码，URL也是乱码

和UTF-8应该没有关系吧

**Comment by Xuanwo** [comment]
你确定一下xml的编码格式呢- -，我没有用过这个插件

**Comment by Xuanwo** [comment]
还有，这个插件好像新版本不能用了？

**Comment by liyaodong** [comment]
我试试吧，解决了提个 pull-request

作者如果不更新的话不如另起一个 repo

**Comment by Xuanwo** [comment]
提PR吧，我可以合并

**Comment by liyaodong** [comment]
`hexo.post.create(data, replace);`

应该是这个函数造成了文件名乱码，似乎不是插件的问题，是`hexo`这个函数得问题

**Comment by liyaodong** [comment]
换了 RSS migrate 发现这个问题解决了，感觉这俩差不多

[hexo-migrator-rss](https://github.com/hexojs/hexo-migrator-rss)

**Comment by Xuanwo** [comment]
看来这个插件已经没有用了？。。

**Comment by liyaodong** [comment]
差不多     关掉 Issue 吧
